### ISSUE TITLE
Nothing returns

### ISSUE THREAD

**Issue by xuyao91** [taufeeque9/HumanFallDetection#13]
Hi
I ran the program and got no error, but nothing returns，
this is logs
```
python fall_detector.py --video=/Users/xuyao/Workspaces/ai/HumanFallDetection/video/1665573678425490.mp4

Starting...
src/openpifpaf/csrc/src/cif_hr.cpp:102: UserInfo: resizing cifhr buffer
src/openpifpaf/csrc/src/occupancy.cpp:53: UserInfo: resizing occupancy buffer
Exiting...

```

**Comment by xinrui98** [comment]
I have the exact same issue, and have no way to save the output as well.

**Comment by taufeeque9** [comment]
The expected output is that the video should play as shown in the readme. Can you specify the Python version you are using? I have tested the library with Python3.9. You can try running the program in a virtual env with Python3.9 installed along with the requirements. 

If this doesn't fix the issue, the problem may be with reading the exact input video. Does the problem persist with any type of video? If not, then you can link the video here, and I can try to run it from my end to debug the issue further. Another thing you can try is to run the program directly with a webcam as: `python fall_detector.py` and see if that works.

**Comment by xinrui98** [comment]
I have tried using python3.9 and have recorded a screen recording to demonstrate my issue. Thanks in advance for your help! https://drive.google.com/file/d/1ITSKGFJr1xDXxlxfWh8SMP3F7Mxp_q5w/view?usp=sharing

**Comment by xinrui98** [comment]
<img width="1638" alt="Screenshot 2022-10-23 at 9 57 07 PM" src="https://user-images.githubusercontent.com/44086084/197396325-bb67a1a5-4c06-45e2-80fa-e0e02ec69754.png">
When I try to use webcam, I will get the above error as well :(

**Comment by taufeeque9** [comment]
I have fixed the error you are getting with the webcam. Let me know if you are able to run the program with a webcam now.

As for the issue with using the video input, I don't see why it is not showing the output. I think the code is running fine, just that OpenCV is not able to start/display the video output. If you're this on a server, then you should first try running the program locally.

**Comment by xinrui98** [comment]
I am running the program locally. Still same issue with Webcam and Video, where it pops up for 1s and exits right after. One thing to note is that I have disabled cuda and am using a Macbook with Intel Chip. Could that be the cause of the problem?

**Comment by taufeeque9** [comment]
I haven't tested it on macOS, so that could be an issue. It could also be an IDE-related issue. Can you directly run the program without the IDE?

Specifically, it seems like PyCharm may cause some trouble with OpenCV: https://stackoverflow.com/questions/64950340/cv2-imshow-is-not-working-properly-in-pycharm-macos

**Comment by xinrui98** [comment]
I am running the program directly on the terminal, where the issue still persists as seen in the video. The only code I changed was changing disable_cuda to default True. Do you think that could have caused the issue? https://drive.google.com/file/d/14XTsND12-luSU19OtAc5Abmyd-yYZiq7/view?usp=sharing

**Comment by taufeeque9** [comment]
I don't think disabling CUDA is the cause of the issue. 

I am also running the program directly through the terminal, although on Ubuntu 18.04.

I would recommend using a debugger to dive deeper into the issue. You can add some breakpoints at various places in the code where the while loop of processing the input could potentially terminate. For example, on lines 268 and 272 of `algorithms.py`.

**Comment by xinrui98** [comment]
I have tried to put some breakpoints at various places. However, since my video do appear (although just for a split second), there isn't any exceptions being thrown. Have you tested the code on Windows as well? Or does it only work on Ubuntu 18.04?
